### ISSUE TITLE
testing in react-create-app stack

### ISSUE THREAD

**Issue by yonatanmn** [alisd23/mobx-react-router#17] opened 2017-04-05 17:13 UTC
Hi. 
I'm using CRA, with mobx, react-router@4 and this project.

In the app itself everything goes well. I have routerStore like example, and I pass history prop to Router. 
I need `withRouter` for every component that uses this functionality but that's fine. 

The problem starts at testing,
I manage to change path from the app (with simulate click on some btn that do `props.history.push('..')` )
with
`
      function assertCorrectPath(ev) {
        expect(ev).toEqual('/');
      }
      MainWrapper.context().router.history.listen(assertCorrectPath);
`
I have it on context thanks to:
[react-router-test-context](https://github.com/pshrmn/react-router-test-context).

But, I cannot be in sync with path when I change it from the test:
I do ` wrapper.context().router.history.push('cc');  `
and the Component is not rendered accordingly.

Is there any easier way for all that?

**Comment by alisd23** [comment] 2017-04-09 21:58
This might be related to #16. I'm about to push a fix for it. Let me know if the issue is still there after trying that version.

**Comment by yonatanmn** [comment] 2017-04-18 14:29
@alisd23 , still not working, tried with @4.0.1:

```js
        // component
        <Route path="/a" render={Layout.renderMainImage} />
```

```js
  //test
 function assertCorrectPath(ev) {
        expect(ev.pathname).toEqual('/a'); //works
        expect(wrapper.find('.welcome-image').length).toEqual(1) // received 0
      }

 wrapper.context().router.history.push('a');
 await wrapper.context().router.history.subscribe(assertCorrectPath);
```

**Comment by alisd23** [comment] 2017-04-19 22:03
Hi, sorry been away for a week. Where is mobx/mobx-react-router actually used in this example?

**Comment by yonatanmn** [comment] 2017-04-20 12:24
file at `stores/Router` is:
```js
import { RouterStore, syncHistoryWithStore } from 'mobx-react-router';

import createBrowserHistory from 'history/createBrowserHistory';
const browserHistory = createBrowserHistory();

const router = new RouterStore();
export const history = syncHistoryWithStore(browserHistory, router);

export default router;
```

**Comment by alisd23** [comment] 2017-04-21 08:08
If you could link the full code example that would be helpful - I can't really see why it's not working with the current code you've given me. The issue might be something more obvious.

**Comment by yonatanmn** [comment] 2017-04-23 15:50
ok, created demo project:
https://github.com/yonatanmn/cra_router

Maybe I'm missing something basic...

**Comment by alisd23** [comment] 2017-04-24 09:36
I'm not really sure to be honest. I haven't seen a setup like that before, but I also think it's unlikely this library is at fault. Closing for now until someone else has any ideas or if you're **sure** it's a bug with this library. :+1:

**Closed by alisd23** 2017-04-24 09:36 UTC

**Comment by yonatanmn** [comment] 2017-04-25 12:11
@alisd23 - what is the recommended setup for mobx-react-router + testing?

**Comment by alisd23** [comment] 2017-04-26 19:34
I suppose that's quite an open ended question. If you're just testing your components in a really isolated way then you can just mock the history, of using mobx-react-router to cause components to re-render.

But I also don't see why using a real mobx store + mobx-react-router **wouldn't** work, it's not particularly complex code behind the scenes. Just try different setups I suppose.

**Comment by yonatanmn** [comment] 2017-04-30 09:00
@alisd23 - I guess it's a setup problem, but I can't figure out what's wrong. 
do you have by any chance a create-react-app project with mobx-react-router so I can see how you setup-ed your tests?

**Comment by alisd23** [comment] 2017-05-02 08:01
I haven't actually created an app yet with mobx-react-router AND testing. But if I did I would probably not use mobx-react-router in them at all - and instead test components logic in an isolated way, mocking the route changes.

**Comment by yonatanmn** [comment] 2017-05-03 14:50
ok , ill try. thx
