### ISSUE TITLE
[question] this vs react-router-dom

### ISSUE THREAD

**Issue by weisk** [alisd23/mobx-react-router#58] opened 2018-09-18 23:24 UTC
Good job in this library, however, I wonder:

what would be the benefits in keeping the history synced in a store, as opposed to just wrap any component that needs it with the `@withRouter` HOC.

**Comment by alisd23** [comment] 2018-10-01 09:16
Hi, well it's mainly about trying to be consistent by treating location/history state the same as the rest of your mobx state (seeing actions, state changes, etc...). Also it's a unified place to access/change location state from inside *or outside* a component, for example in another store.

Let me know if that doesn't answer your question.

I'll close the issue though because it's not a bug or feature request.

**Closed by alisd23** 2018-10-01 09:16 UTC
